services:
  web:
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./redbit:/app/redbit
      - /app/redbit/staticfiles 
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/data/postgres
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
